name: CI Pipeline

on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        java: [21]

    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify Formatting
        run: mvn verify --checkstyle.skip --errors --batch-mode

      - name: Compilation
        run: mvn compile --batch-mode

      - name: Tests
        run: mvn test --batch-mode
