name: Java CI with Maven

on:
  push:
    branches: [ main, develop, security-tools ]
  pull_request:
    branches: [ main, develop, security-tools ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    continue-on-error: false

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Validate
        run: mvn validate

      - name: Compile
        run: mvn compile

      - name: Build
        run: mvn -B package --file pom.xml

      - name: Test
        run: mvn test

      - name: Verify
        run: mvn verify

  security:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    continue-on-error: true

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-20@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif